import React, { useState } from "react";
import { TextField, Box, IconButton, Tooltip, Button } from "@mui/material";
import CopyAllIcon from "@mui/icons-material/CopyAll";
import { useCreateSignUpApiMutation } from "@/redux/api/signup/signUpApiSlice";
import UserDetailsModal from "../Modals/UserDetailsModal";

interface Step3GenerateCredentialsProps {
  name: string;
}

const Step3GenerateCredentials: React.FC<Step3GenerateCredentialsProps> = ({
  name,
}) => {
  // Process the name to create email
  const trimmedName = name.trim().toLowerCase().replace(/\s+/g, "");
  const email = `${trimmedName}@dinefy.ca`;

  // Generate a random password
  const generatePassword = () => {
    const chars =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()";
    let password = "";
    for (let i = 0; i < 12; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return password;
  };
  const password = generatePassword();

  // Copy email and password to clipboard
  const handleCopy = () => {
    const copyText = `Email: ${email}\nPassword: ${password}`;
    navigator.clipboard.writeText(copyText).then(() => {
      alert("Credentials copied to clipboard!");
    });
  };

  // State for opening the modal
  const [open, setOpen] = useState(false);
  const [userId, setUserId] = useState<string | undefined>(undefined); // State to hold user ID

  // Add to system
  const [createSignUpApi] = useCreateSignUpApiMutation();

  const handleAddToSystem = async () => {
    try {
      const response = await createSignUpApi({ email, password }).unwrap();
      console.log(response);

      // Set user ID and open the modal
      const userId = await response?.user?.id; // Access the id from the nested user object
      setUserId(userId);
      setOpen(true);
    } catch (error: any) {
      console.log(error.message);
    }
  };

  return (
    <Box className="space-y-4">
      <div>
        <label>Email</label>
        <TextField
          value={email}
          disabled
          fullWidth
          variant="outlined"
          className="mt-2"
        />
      </div>
      <div>
        <label>Autogenerated Password</label>
        <TextField
          value={password}
          disabled
          fullWidth
          variant="outlined"
          className="mt-2"
        />
      </div>
      <div className="flex justify-end mt-4 space-x-2">
        <Tooltip title="Copy Credentials">
          <IconButton onClick={handleCopy} color="primary">
            <CopyAllIcon />
          </IconButton>
        </Tooltip>

        {/* Add to System button */}
        <Tooltip title="Add to System">
          <Button
            onClick={handleAddToSystem}
            variant="contained"
            color="secondary"
          >
            Add to System
          </Button>
        </Tooltip>
      </div>

      {/* Pass the userId to the modal */}
      <UserDetailsModal
        open={open}
        onClose={() => setOpen(false)}
        userId={userId} // Only passing the userId here
      />
    </Box>
  );
};

export default Step3GenerateCredentials;
